In [1]:
from src.stage.ambulatorio import read as stage_read

df_ambulatorio = stage_read()
df_ambulatorio

,Subrubro Prestacion Gerencia Estrategica,Periodo,Rubro Prestacion Gerencia Estrategica,Subzona Direccion Comercial Asociado,Zona Direccion Comercial Asociado,Fecha Proceso Autorización,Cantidad Prestaciones Aceptadas
0,F/D,202510,F/D,SALTA,NOA,2025-10-01,0
1,Densitometria,202510,Imagenes,TUCUMAN,NOA,2025-10-01,1
2,Densitometria,202510,Imagenes,SALTA,NOA,2025-10-01,3
3,Densitometria,202510,Imagenes,MENDOZA,CUYO,2025-10-01,3
4,Densitometria,202510,Imagenes,SAN LUIS,CUYO,2025-10-01,1
...,...,...,...,...,...,...,...
361018,Videoconsulta Guardia,202606,Consulta,CABA SUR,AMBA,2026-06-21,1
361019,Videoconsulta Guardia,202606,Consulta,GBA NORTE,AMBA,2026-06-21,16
361020,Videoconsulta Guardia,202606,Consulta,GBA OESTE,AMBA,2026-06-21,52
361021,Videoconsulta Guardia,202606,Consulta,GBA SUR,AMBA,2026-06-21,31
361022,Videoconsulta Guardia,202606,Consulta,LA PLATA,PROVINCIA BS AS,2026-06-21,2

In [2]:
df_ambulatorio.rename(columns={'Rubro Prestacion Gerencia Estrategica':'Rubro GE',
                                                'Subrubro Prestacion Gerencia Estrategica':'Subrubro GE',
                                                'Zona Direccion Comercial Asociado':'Zona DCA',
                                                'Subzona Direccion Comercial Asociado':'Subzona DCA',
                                                'Fecha Proceso Autorización':'Fecha',
                                                'Cantidad Prestaciones Aceptadas':'Q'}, inplace=True)

In [3]:
df_ambulatorio

,Subrubro GE,Periodo,Rubro GE,Subzona DCA,Zona DCA,Fecha,Q
0,F/D,202510,F/D,SALTA,NOA,2025-10-01,0
1,Densitometria,202510,Imagenes,TUCUMAN,NOA,2025-10-01,1
2,Densitometria,202510,Imagenes,SALTA,NOA,2025-10-01,3
3,Densitometria,202510,Imagenes,MENDOZA,CUYO,2025-10-01,3
4,Densitometria,202510,Imagenes,SAN LUIS,CUYO,2025-10-01,1
...,...,...,...,...,...,...,...
361018,Videoconsulta Guardia,202606,Consulta,CABA SUR,AMBA,2026-06-21,1
361019,Videoconsulta Guardia,202606,Consulta,GBA NORTE,AMBA,2026-06-21,16
361020,Videoconsulta Guardia,202606,Consulta,GBA OESTE,AMBA,2026-06-21,52
361021,Videoconsulta Guardia,202606,Consulta,GBA SUR,AMBA,2026-06-21,31
361022,Videoconsulta Guardia,202606,Consulta,LA PLATA,PROVINCIA BS AS,2026-06-21,2

In [4]:
from src.utils.mapping import amb_rubros_subrubros

amb_rubros_subrubros(df_ambulatorio)

Consultando datos en el rango: amb_rubro!A1:C19...
Consultando datos en el rango: amb_subrubro!A1:D90...
Mapeo de rubros y subrubros aplicado correctamente.

,Subrubro GE,Periodo,Rubro GE,Subzona DCA,Zona DCA,Fecha,Q,Subrubro PPTO,Rubro PPTO
0,F/D,202510,F/D,SALTA,NOA,2025-10-01,0,Resto,Resto
1,Densitometria,202510,Imagenes,TUCUMAN,NOA,2025-10-01,1,Img. Otras Bajo Costo,Imagenes
2,Densitometria,202510,Imagenes,SALTA,NOA,2025-10-01,3,Img. Otras Bajo Costo,Imagenes
3,Densitometria,202510,Imagenes,MENDOZA,CUYO,2025-10-01,3,Img. Otras Bajo Costo,Imagenes
4,Densitometria,202510,Imagenes,SAN LUIS,CUYO,2025-10-01,1,Img. Otras Bajo Costo,Imagenes
...,...,...,...,...,...,...,...,...,...
361018,Videoconsulta Guardia,202606,Consulta,CABA SUR,AMBA,2026-06-21,1,Con. Videoconsulta,Consulta
361019,Videoconsulta Guardia,202606,Consulta,GBA NORTE,AMBA,2026-06-21,16,Con. Videoconsulta,Consulta
361020,Videoconsulta Guardia,202606,Consulta,GBA OESTE,AMBA,2026-06-21,52,Con. Videoconsulta,Consulta
361021,Videoconsulta Guardia,202606,Consulta,GBA SUR,AMBA,2026-06-21,31,Con. Videoconsulta,Consulta
361022,Videoconsulta Guardia,202606,Consulta,LA PLATA,PROVINCIA BS AS,2026-06-21,2,Con. Videoconsulta,Consulta

In [6]:
from src.utils.gc_functions import leer_tabla_df

ne_amb = leer_tabla_df('1RV39I7zo0rSBgDhmGHjaEPt0eBnLfle1L0XpvLIHI9M','NE_amb!A1:F47629')
ne_amb

Consultando datos en el rango: NE_amb!A1:F47629...

,Rubro PPTO,Subrubro PPTO,Zona DCA,Subzona DCA,Periodo,NE
0,Anestesia,Anestesia,AMBA,CABA CENTRO,202510,35
1,Anestesia,Anestesia,AMBA,CABA NORTE,202510,18
2,Anestesia,Anestesia,AMBA,CABA OESTE,202510,28
3,Anestesia,Anestesia,AMBA,CABA SUR,202510,5
4,Anestesia,Anestesia,AMBA,GBA NORTE,202510,40
...,...,...,...,...,...,...
47623,Salud Mental,Salud Mental,SANTA FE,STA FE CAP. + LAS COLONIAS,202705,29
47624,Salud Mental,Salud Mental,SANTA FE,RAFAELA/SUNCHALES,202706,1511
47625,Salud Mental,Salud Mental,SANTA FE,SANTA FE NORTE,202706,236
47626,Salud Mental,Salud Mental,SANTA FE,SANTA FE SUR,202706,3093
47627,Salud Mental,Salud Mental,SANTA FE,STA FE CAP. + LAS COLONIAS,202706,29